fix(stats): fix windows directory for auto-install
harbassan/spicetify-apps pull request #158
Opened 2024-10-29 09:56 UTC by cyjico

Fixes #157 (You may close that now).

Should point to the correct directory now according to the [docs](https://spicetify.app/docs/advanced-usage/custom-apps).

2024-10-29 10:55 UTC, rxri commented
This is still wrong. $env:APPDATA + you still didn't address the other issue I was talking about.

2024-10-29 23:53 UTC, cyjico commented
I'll fix it tomorrow. I have to attend my classes today 😞.

2024-10-30 07:11 UTC, cyjico commented
@rxri Can you check if its ok? Thanks in advance!!!!

Also, I noticed the same issue with the bash script (of grabbing the incorrect file).

2024-10-30 18:01 UTC, rxri requested changes

2024-10-30 18:01 UTC, rxri commented on stats/install.ps1
> +$customAppsDir = "$env:APPDATA\Roaming\spicetify\CustomApps"
```suggestion
$customAppsDir = "$env:APPDATA\spicetify\CustomApps"
```

2025-02-20 02:08 UTC, merged